Nuevo juego
ITIC-ITESME/juego-Franjmc13 pull request #1
Opened 2021-11-14 01:54 UTC by Franjmc13

Se agrego un nuevo juego de dados utilizando el modulo random

2021-11-14 02:13 UTC, ingrafaelcr commented
Se encuentra en verificación la funcionalidad que enviaste.

2021-11-15 00:59 UTC, Franjmc13 commented
Enterado estoy en espera, por cualquier duda

2021-11-15 01:04 UTC, ingrafaelcr requested changes
Se verificaron las modificaciones, están perfectas, agrega en el README los datos de los juegos.

2021-11-15 01:06 UTC, Franjmc13 commented
Enterado modificare el README

2021-11-15 01:20 UTC, ingrafaelcr approved these changes
Listo, se enviara a merga

2021-11-15 01:20 UTC, merged